services:
  nginx:
    container_name: nginx-dev
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./ssl:/ssl

  automatization:
    container_name: automat-dev
    restart: unless-stopped
    build: ./automatization
    # ports:
    #   - "6004:5000" # Optional for debugging
    environment:
      - VERSION=8.3.0
      - SCRIPTS_PATH=/scripts
      - VM_VCENTER_IP=${VM_VCENTER_IP}
      - VM_VCENTER_USER=${VM_VCENTER_USER}
      - VM_VCENTER_PASSWORD=${VM_VCENTER_PASSWORD}
    volumes:
      - ./automatization/scripts:/scripts

  backend:
    container_name: backend-dev
    restart: unless-stopped
    build: ./backend
    # ports:
    #   - "6002:5000" # Optional for debugging
    environment:
      - VERSION=8.4.1
      - DB_CONNECTION_STRING=server=${DB_ADDRESS};database=${DB_NAME};port=${DB_PORT};user=${DB_USER};password=${DB_PASSWORD};
      - SALT=fE6CNRT0ch244bwK4kr14Ho14GcNNC
      - AUTOMATIZATION_URL=http://automatization:5000
      - EMAIL_TEMPLATES=/app/EmailTemplates/
      - MAIL_SMTP_ADDRESS=${MAIL_SMTP_ADDRESS}
      - MAIL_SMTP_PORT=${MAIL_SMTP_PORT}
      - MAIL_LOGIN=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - UNIT_TESTING=
      - AUTO_MIGRATIONS=true
      - USE_SWAGGER=true
      - ALLOW_CORS=true
      - AD_CONNECTION_STRING=${AD_ADDRESS}__${AD_DOMAIN}__${AD_USER}__${AD_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Development # Temporary. Remove in production

  frontend:
    container_name: frontend-dev
    build: ./frontend
    # ports:
    #   - 6003:6003 # Optional for debugging
    environment:
      - PORT=6003
      - PUBLIC_VERSION=8.2.0
      - PUBLIC_CLIENT_API=/api
      - PUBLIC_BACKEND_API=http://backend:5000
  
  db-backup:
    build: ./backup
    container_name: backup-dev
    restart: unless-stopped
    volumes:
      - ./backup/backup-files:/backup
      - ./backup/backup_script.sh:/etc/periodic/daily/backup_script.sh
    environment:
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
