services:
  nginx:
    depends_on:
      - backend
      - frontend
    container_name: booking-nginx
    restart: unless-stopped
    build: ./nginx
    ports:
      - "80:80"

  backend:
    container_name: booking-backend
    restart: unless-stopped
    build: ./backend
    # ports:
    #   - "6002:5000" # Optional for debugging
    environment:
      - AUTO_MIGRATIONS=true
      - USE_SWAGGER=false
      - ALLOW_CORS=true
      - JWT_SECRET=${JWT_SECRET}
      - DOMAIN_ADDRESS=${DOMAIN_ADDRESS}
      - DB_CONNECTION_STRING=server=db;database=${DB_NAME};port=3306;user=root;password=${DB_PASSWORD};
      - SMTP_CONNECTION_STRING=${SMTP_ADDRESS}__${SMTP_PORT}__${SMTP_USER}__${SMTP_PASSWORD}
      - EMAIL_TEMPLATES_PATH=/app/src/emails/
      - PROXMOX_ADDR=${PROXMOX_ADDR}
      - PROXMOX_TOKEN_ID=${PROXMOX_TOKEN_ID}
      - PROXMOX_TOKEN_SECRET=${PROXMOX_TOKEN_SECRET}
      - PROXMOX_ISO_STORAGE=${PROXMOX_ISO_STORAGE}

  frontend:
    container_name: booking-frontend
    restart: unless-stopped
    build: ./frontend
    # ports:
    #   - 6003:6003 # Optional for debugging
    environment:
      - PORT=6003
      - PUBLIC_VERSION=8.2.0
      - PUBLIC_CLIENT_API=/api
      - PUBLIC_BACKEND_API=http://backend:5000

  db:
    image: mysql
    container_name: booking-db
    restart: unless-stopped

    # ports:
    #   - 3306:3306 # Optional for debugging
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./db/storage:/var/lib/mysql

  adminer:
    image: adminer
    container_name: booking-adminer
    restart: unless-stopped
    ports:
      - 7000:8080

  db-backup:
    build: ./backup
    container_name: booking-backup
    restart: unless-stopped
    ports:
      - "7001:5000" # Optional for debugging
    volumes:
      - ./backup/backup-files:/backup
    environment:
      - ACCESS_PASS=${ACCESS_PASS}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - BACKUP_DIRECTORY=/backup
