services:
  nginx:
    container_name: nginx-dev
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./ssl:/ssl

  automatization:
    container_name: automat-dev
    restart: unless-stopped
    build: ./automatization
    ports:
      - "6004:5000" # Optional for debugging
    environment:
      - VERSION=8.3.0
      - SCRIPTS_PATH=/scripts
      - VM_VCENTER_IP=${VM_VCENTER_IP}
      - VM_VCENTER_USER=${VM_VCENTER_USER}
      - VM_VCENTER_PASSWORD=${VM_VCENTER_PASSWORD}
      - VM_CLUSTER_NAME=${VM_VCENTER_CLUSTER}
      - VM_DATASTORE_NAME=${VM_VCENTER_DATASTORE}
    volumes:
      - ./automatization/app:/app
      - ./automatization/build:/build
      - ./automatization/scripts:/scripts

  backend:
    container_name: backend-dev
    restart: unless-stopped
    build: ./backend
    ports:
      - "6002:5000" # Optional for debugging
    environment:
      - VERSION=${VERSION}
      - TEST_MODE=${TEST_MODE}
      - JWT_SECRET=${JWT_SECRET}
      - DEVOPS_URL=http://automatization:5000
      - DB_CONNECTION_STRING=server=${DB_ADDRESS};database=${DB_NAME};port=${DB_PORT};user=${DB_USER};password=${DB_PASSWORD};
      - AD_CONNECTION_STRING=${AD_ADDRESS}__${AD_DOMAIN}__${AD_USER}__${AD_PASSWORD}
      - SMTP_CONNECTION_STRING=${SMTP_ADDRESS}__${SMTP_PORT}__${SMTP_USER}__${SMTP_PASSWORD}
      - EMAIL_TEMPLATES_PATH=/app/src/emails/
      - VM_ROOT_PASSWORD=${VM_ROOT_PASSWORD}
      - VM_DEFAULT_USER=${VM_DEFAULT_USER}
      - AUTO_MIGRATIONS=true
      - USE_SWAGGER=true
      - ALLOW_CORS=true
    volumes:
      - ./backend/app:/app
      - ./backend/build:/build

  frontend:
    container_name: frontend-dev
    build: ./frontend
    # ports:
    #   - 6003:6003 # Optional for debugging
    environment:
      - PORT=6003
      - PUBLIC_VERSION=8.2.0
      - PUBLIC_CLIENT_API=/api
      - PUBLIC_BACKEND_API=http://backend:5000
    volumes:
      - ./frontend/app:/app
      - ./frontend/build:/build
  
  db-backup:
    build: ./backup
    container_name: backup-dev
    restart: unless-stopped
    volumes:
      - ./backup/backup-files:/backup
      - ./backup/backup_script.sh:/etc/periodic/daily/backup_script.sh
    environment:
      - DB_CONNECTION_STRING=server=${DB_ADDRESS};database=${DB_NAME};port=${DB_PORT};user=${DB_USER};password=${DB_PASSWORD};
