services:
  nginx:
    container_name: nginx-dev
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./ssl:/ssl

  backend:
    container_name: backend-dev
    restart: unless-stopped
    build: ./backend
    ports:
      - "6002:5000" # Optional for debugging
    environment:
      - VERSION=${VERSION}
      - JWT_SECRET=${JWT_SECRET}
      - DB_CONNECTION_STRING=server=${DB_ADDRESS};database=${DB_NAME};port=${DB_PORT};user=${DB_USER};password=${DB_PASSWORD};
      - SMTP_CONNECTION_STRING=${SMTP_ADDRESS}__${SMTP_PORT}__${SMTP_USER}__${SMTP_PASSWORD}
      - EMAIL_TEMPLATES_PATH=/app/src/emails/
      - VM_ROOT_PASSWORD=${VM_ROOT_PASSWORD}
      - VM_DEFAULT_USER=${VM_DEFAULT_USER}
      - SCRIPTS_PATH=/scripts
      - VM_DATACENTER=${VM_DATACENTER}
      - VM_VCENTER_IP=${VM_VCENTER_IP}
      - VM_VCENTER_USER=${VM_VCENTER_USER}
      - VM_VCENTER_PASSWORD=${VM_VCENTER_PASSWORD}
      - VM_CLUSTER_NAME=${VM_VCENTER_CLUSTER}
      - VM_DATASTORE_NAME=${VM_VCENTER_DATASTORE}
      - AUTO_MIGRATIONS=true
      - USE_SWAGGER=true
      - ALLOW_CORS=true
    volumes:
      - ./backend/app:/app
      - ./backend/build:/build
      - ./backend/scripts:/scripts

  frontend:
    container_name: frontend-dev
    build: ./frontend
    # ports:
    #   - 6003:6003 # Optional for debugging
    environment:
      - PORT=6003
      - PUBLIC_VERSION=8.2.0
      - PUBLIC_CLIENT_API=/api
      - PUBLIC_BACKEND_API=http://backend:5000
    volumes:
      - ./frontend/app:/app
      - ./frontend/build:/build

  db:
    image: mysql
    container_name: db-dev
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./db/storage:/var/lib/mysql

  db-backup:
    build: ./backup
    container_name: backup-dev
    restart: unless-stopped
    volumes:
      - ./backup/backup-files:/backup
      - ./backup/restore-backup:/restore
      - ./backup/backup_script.sh:/etc/periodic/daily/backup_script.sh
    environment:
      - HOST=${DB_ADDRESS}
      - DATABASE=${DB_NAME}
      - PORT=${DB_PORT}
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
