services:
  nginx:
    depends_on:
      - backend
      - frontend
    container_name: nginx-dev
    restart: unless-stopped
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/templates
      - ./ssl:/ssl

  backend:
    container_name: backend-dev
    restart: unless-stopped
    build: ./backend
    # ports:
    #   - "6002:5000" # Optional for debugging
    environment:
      - AUTO_MIGRATIONS=true
      - USE_SWAGGER=true
      - ALLOW_CORS=true
      - JWT_SECRET=${JWT_SECRET}
      - DB_CONNECTION_STRING=server=${DB_ADDRESS};database=${DB_NAME};port=${DB_PORT};user=${DB_USER};password=${DB_PASSWORD};
      - SMTP_CONNECTION_STRING=${SMTP_ADDRESS}__${SMTP_PORT}__${SMTP_USER}__${SMTP_PASSWORD}
      - EMAIL_TEMPLATES_PATH=/app/src/emails/
      - PROXMOX_ADDR=${PROXMOX_ADDR}
      - PROXMOX_TOKEN_ID=${PROXMOX_TOKEN_ID}
      - PROXMOX_TOKEN_SECRET=${PROXMOX_TOKEN_SECRET}
      - PROXMOX_ISO_STORAGE=${PROXMOX_ISO_STORAGE}

  frontend:
    container_name: frontend-dev
    build: ./frontend
    # ports:
    #   - 6003:6003 # Optional for debugging
    environment:
      - PORT=6003
      - PUBLIC_VERSION=8.2.0
      - PUBLIC_CLIENT_API=/api
      - PUBLIC_BACKEND_API=http://backend:5000

  db:
    image: mysql
    container_name: db-dev
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./db/storage:/var/lib/mysql

  db-backup:
    build: ./backup
    container_name: backup-dev
    restart: unless-stopped
    volumes:
      - ./backup/backup-files:/backup
      - ./backup/restore-backup:/restore
      - ./backup/backup_script.sh:/etc/periodic/daily/backup_script.sh
    environment:
      - HOST=${DB_ADDRESS}
      - DATABASE=${DB_NAME}
      - PORT=${DB_PORT}
      - USER=${DB_USER}
      - PASSWORD=${DB_PASSWORD}
