services:
  db:
    image: mysql
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./storage:/var/lib/mysql
